### ISSUE TITLE
[CI] Add seperate workflow for pull request and fix script

### ISSUE THREAD

**Issue by abdmmar** [abdmmar/wiki-img-meta#3]
## Overview
To run a workflow on pull requests to check code quality and not publish the package, it's must create a new file for it.

## Tasks:
- [x] make seperate file for pull request: `pull-request.yml`
- [x] change name from `workflow.yml` to `publish.yml`
- [x] change script from `npm i` to `npm ci`
- [x] make seperate script for linting, formating, testing, and coverage
